### ISSUE TITLE
creating db and migrationn

### ISSUE THREAD

**Issue by mach37** [magul/asm3#1]
hello, great app, I am having some trouble with the db creation. maint_db_install

I am trying it, I am having trouble with the DB creation, can you please tell me which file creates the database,
I would like to fork am trying to port to mongo, and sql express free, any pointers on where to start would help.

Can you please add the just a regular `dbCreate.Sql` file,  or the output sql file to the repo here I [found this](https://github.com/magul/asm3/blob/ba16759586e825b0272e7f94ac8782c7040d756b/src/dbupdate.py), but I am not sure if thats the correct file

**Comment by magul** [comment]
Hi @mach37, this repository was only a mirror of official asm3 hosted previously on self-hosted server.

As far as I know right now they migrated to github and official repo is available under [bobintetley/asm3](https://github.com/bobintetley/asm3).

I'm closing this one and feel free to open new one there.

CC: @bobintetley
